require './assignSpec'
require './convertSpec'
require './convertValueSpec'
require './parseKeyNameSpec'
require './transposeSpec'
require './validateOptionsSpec'
require './processFileSpec'
require './regressionSpec'
